function [DrivingWheels, directionState, turncounter, numberOfTurns] = drive (DriveWheelsPort,...
                                                                              SteeringWheelsPort,...
                                                                              LightSensorLPort,...
                                                                              LightSensorRPort,...
                                                                              ColorSensorPort,...
                                                                              turncounter,... 
                                                                              directionState,...
                                                                              numberOfTurns)
                                                                          
%%% DRIVE FUNCTION; MIXED OUTPUT
%
%   drive function is called by the main function to set the robot going.
%   It in itself calls the followLane function to check if there is a turn
%   needed to be carried out. Regardless it provides constant power to the
%   drive axle.
%
%%%
                                                                          
                                                                          
% Feeding power to the drive axle
DrivingWheels = NXTMotor(DriveWheelsPort, 'TachoLimit', 0, 'Power', 6);
DrivingWheels.SendToNXT();

% Setting the power for the steering axle
power = -100;

% Calling the followLane function to check if any turns are needed to be
% taken

[directionState, turncounter, numberOfTurns] = followLane(LightSensorLPort,...
                                                          LightSensorRPort,...
                                                          ColorSensorPort,...
                                                          power,...
                                                          directionState,...
                                                          SteeringWheelsPort,...
                                                          DriveWheelsPort,...
                                                          turncounter, ...
                                                          numberOfTurns);
    
end